from enum import StrEnum

# ---------------------------------
# Audit Immutable Trail for Actions
# --------------------------------- 
class AuditActions(StrEnum):

    PATIENT_CREATED = "PATIENT_CREATED"
    PATIENT_UPDATED = "PATIENT_UPDATED"

    ONBOARDING_EMAIL_SENT = "ONBOARDING_EMAIL_SENT"
    ONBOARDING_EMAIL_FAILED = "ONBOARDING_EMAIL_FAILED"

    EVENT_DEAD_LETTERED = "EVENT_DEAD_LETTERED"
    EVENT_REPLAYED = "EVENT_REPLAYED"

    ORGANIZATION_CREATED = "ORGANIZATION_CREATED"
    PRACTITIONER_CREATED = "PRACTITIONER_CREATED"